// NOTE it's a fake data which need to be deleted when API will give more list

export default {
  data: [
    {
      id: 876,
      origin_terminal: {
        id: 12,
        name: 'Port Vostochniy Terminal',
        port_name: 'Vostochniy',
      },
      destination_terminal: {
        id: 34,
        name: 'Dubai World',
        port_name: 'Hong Kong',
      },
      service_code: 'West Service 12',
      etd_at: '2019-09-18T18:45:09.000Z',
      eta_at: '2019-09-29T12:12:09.000Z',
      nb_teu: 470,
      teu_visible: true,
      for_sale: true,
      for_swap: true,
      price_teu: 345,
      price_feu: 890,
      whitelist_owners: 'Seaco,Cosco,Hapag-Lloyd',
      expiry_offer_at: '2019-02-29T08:12:09.000Z',
      contact_email: 'capacity.user@gmail.com',
      company_name: 'Maersk',
    },
    {
      id: 882,
      origin_terminal: {
        id: 32,
        name: 'Ningbo Meishan Island International',
        port_name: 'Ningbo',
      },
      destination_terminal: {
        id: 64,
        name: 'Container Terminal',
        port_name: 'Salalah',
      },
      service_code: 'TP West 34',
      etd_at: '2019-10-06T18:45:09.000Z',
      eta_at: '2019-11-15T12:12:09.000Z',
      nb_teu: 250,
      teu_visible: true,
      for_sale: true,
      for_swap: false,
      price_teu: 385,
      price_feu: 850,
      whitelist_owners: 'Seacube,One,Hapag-Lloyd',
      expiry_offer_at: '2019-11-01T08:12:09.000Z',
      contact_email: 'capacity.central@gmail.com',
      company_name: '',
    },
    {
      id: 883,
      origin_terminal: {
        id: 32,
        name: 'Belgium',
        port_name: 'Antwerp',
      },
      destination_terminal: {
        id: 64,
        name: 'Container Terminal',
        port_name: 'Singapore',
      },
      service_code: 'TP West 34',
      etd_at: '2019-11-12T18:45:09.000Z',
      eta_at: '2019-12-16T12:12:09.000Z',
      nb_teu: 630,
      teu_visible: true,
      for_sale: true,
      for_swap: true,
      price_teu: 325,
      price_feu: 990,
      whitelist_owners: 'Seacube,One,Hapag-Lloyd',
      expiry_offer_at: '2019-11-01T08:12:09.000Z',
      contact_email: 'capacity.central@gmail.com',
      company_name: '',
    },
    {
      id: 884,
      origin_terminal: {
        id: 32,
        name: 'U.S.A.',
        port_name: 'Los Angeles',
      },
      destination_terminal: {
        id: 64,
        name: 'Container Terminal',
        port_name: 'Shenzhen, China',
      },
      service_code: 'TP West 34',
      etd_at: '2019-05-06T18:45:09.000Z',
      eta_at: '2019-09-13T12:12:09.000Z',
      nb_teu: 7850,
      teu_visible: true,
      for_sale: true,
      for_swap: false,
      price_teu: 295,
      price_feu: 780,
      whitelist_owners: 'Seacube,One,Hapag-Lloyd',
      expiry_offer_at: '2019-11-01T08:12:09.000Z',
      contact_email: 'capacity.central@gmail.com',
      company_name: '',
    },
    {
      id: 885,
      origin_terminal: {
        id: 32,
        name: 'Greece',
        port_name: 'Piraeus',
      },
      destination_terminal: {
        id: 64,
        name: 'Container Terminal',
        port_name: 'Guangzhou Harbor, China',
      },
      service_code: 'TP West 34',
      etd_at: '2019-03-06T18:45:09.000Z',
      eta_at: '2019-06-13T12:12:09.000Z',
      nb_teu: 410,
      teu_visible: true,
      for_sale: true,
      for_swap: false,
      price_teu: 365,
      price_feu: 680,
      whitelist_owners: 'Seacube,One,Hapag-Lloyd',
      expiry_offer_at: '2019-11-01T08:12:09.000Z',
      contact_email: 'capacity.central@gmail.com',
      company_name: '',
    },
    {
      id: 886,
      origin_terminal: {
        id: 32,
        name: '',
        port_name: 'Manila, Philippines',
      },
      destination_terminal: {
        id: 64,
        name: 'Container Terminal',
        port_name: 'Busan, South Korea',
      },
      service_code: 'TP West 34',
      etd_at: '2019-07-01T18:45:09.000Z',
      eta_at: '2019-12-11T12:12:09.000Z',
      nb_teu: 520,
      teu_visible: true,
      for_sale: true,
      for_swap: true,
      price_teu: 510,
      price_feu: 1120,
      whitelist_owners: 'Seacube,One,Hapag-Lloyd',
      expiry_offer_at: '2019-11-01T08:12:09.000Z',
      contact_email: 'capacity.central@gmail.com',
      company_name: '',
    },
    {
      id: 887,
      origin_terminal: {
        id: 32,
        name: 'Ningbo Meishan Island International',
        port_name: 'Hanshin Port, Japan',
      },
      destination_terminal: {
        id: 64,
        name: 'Container Terminal',
        port_name: 'Rotterdam, The Netherlands',
      },
      service_code: 'TP West 34',
      etd_at: '2019-01-02T18:45:09.000Z',
      eta_at: '2019-07-02T12:12:09.000Z',
      nb_teu: 480,
      teu_visible: true,
      for_sale: true,
      for_swap: true,
      price_teu: 820,
      price_feu: 1890,
      whitelist_owners: 'Seacube,One,Hapag-Lloyd',
      expiry_offer_at: '2019-11-01T08:12:09.000Z',
      contact_email: 'capacity.central@gmail.com',
      company_name: '',
    },
    {
      id: 888,
      origin_terminal: {
        id: 32,
        name: 'Ningbo Meishan Island International',
        port_name: 'Colombo, Sri Lanka',
      },
      destination_terminal: {
        id: 64,
        name: 'Container Terminal',
        port_name: 'Hamburg, Germany',
      },
      service_code: 'TP West 34',
      etd_at: '2019-12-08T18:45:09.000Z',
      eta_at: '2019-12-07T12:12:09.000Z',
      nb_teu: 320,
      teu_visible: true,
      for_sale: true,
      for_swap: false,
      price_teu: 1345,
      price_feu: 8790,
      whitelist_owners: 'Seacube,One,Hapag-Lloyd',
      expiry_offer_at: '2019-11-01T08:12:09.000Z',
      contact_email: 'capacity.central@gmail.com',
      company_name: '',
    },
  ],
};
